# Generated by Django 5.1.3 on 2024-12-01 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trivias_completed', models.PositiveIntegerField(default=0)),
                ('lives', models.PositiveIntegerField(default=3)),
                ('active_skin', models.CharField(default='TerryNice', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terry_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
