# Generated by Django 5.1.1 on 2024-12-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Terry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='active_skin',
            field=models.CharField(default='TerryNice.gif', max_length=100),
        ),
    ]
