# Generated by Django 5.1.3 on 2024-12-02 04:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Terry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='consecutive_trivias',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_trivia_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
