# Generated by Django 5.1.1 on 2024-12-02 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Terry', '0002_alter_userprofile_active_skin'),
        ('Terry', '0003_userprofile_consecutive_failedtrivias'),
    ]

    operations = [
    ]
