# Generated by Django 5.1.1 on 2024-11-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ususarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('contraseña', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
