# Generated by Django 5.1.1 on 2024-11-26 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ususarios',
            new_name='Usuarios',
        ),
    ]
