# Generated by Django 5.1.1 on 2024-12-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
